[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=--entry=kernel_main",
    "-C", "link-arg=--image-base=0x100000",
    "-C", "relocation-model=static",
]
